#!/bin/sh
if mountpoint -q /target; then
  echo "Copying tarsnap  to /target"
  cp /tmp/tarsnap*.deb /target
else
  echo "/target is not a mountpoint."
  echo "You can either:"
  echo "- re-run this container with -v /tmp:/target"
  echo "- extract the deb package (located at /tmp)"
fi
